### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by varyamereon** [BottlecapDave/HomeAssistant-OutlookCalendar#5]
I'm not sure if this component is still being developed but I am unable to authorize. I always get this page:

We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

I'm not sure if it's something I'm doing or something that has change since this component was last updated.

**Comment by Sebbs128** [comment]
The Redirect URI you enter in AAD > Home Assistant > Authentication must match the URL passed through from the "Link Outlook Calendar account" hyperlink. It must also start with "https" or "http://localhost".

Copy the link for linking your Microsoft account, and have a look at the redirect_uri parameter in that URL. For example, mine is
`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=[client_id]&redirect_uri=http%3A%2F%2F10.0.0.10%3A8123%2Fapi%2Fmicrosoft-outlook-calendar&scope=Calendars.Read+offline_access&state=[state]`.

In my case, I need to enable HTTPS on my HA install (don't ask me how to do that; I'm still trying to find it), and update the Redirect URI to `https://10.0.0.10:8123/api/microsoft-outlook-calendar`

Edit: Because I'm not exposing HA to the internet (yet), I followed the info at https://www.floriangaechter.com/blog/valid-https-certificate-for-local-home-assistant-installation/ to create and add some self-signed certs to HA, which let me complete the authorization.

**Comment by BottlecapDave** [comment]
Hello, sorry I didn't get a chance to look at your issue.

This component has been archived in favour of https://github.com/PTST/O365-HomeAssistant. A fork of this component exists at https://github.com/BottlecapDave/O365-HomeAssistant/tree/feature/configurable-scopes which includes support for restricting access to read only to match this component.
